import Head from "next/head";

import { Heading } from "@ignite-ui/react";
import { Container, Hero, Preview } from "./styles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Container>
          <Hero></Hero>
          <Preview></Preview>
        </Container>
      </div>
    </>
  );
}
